
variable "Org" {}
variable "AZRegion" {}
variable "LZType" {}
variable "Env" {}
variable "location" {}
variable "Tags" {}
variable "vnet_pip_alloc_method" {}
variable "vnet_pip_sku" {}
variable "vnet_pip_zones" {}
variable "vnet_type" {}
variable "vnet_vpn_type" {}
variable "vnet_generation" {}
variable "vnet_active_active" {}
variable "vnet_enable_bgp" {}
variable "vnet_sku" {}
variable "vnetgateway_rg" {}
variable "vnet_aad_audiance" {}
variable "vpnclient_address_space" {}
variable "vpn_client_protocols" {}
variable "gatewaysnet" {}
variable "vpn_auth_types" {}
variable "vnet_tenant" {}