variable "location" {}
variable "Tags" {}
variable "Org_caps" {}
variable "peo_caps" {}
#variable "rtypes_caps" {} 
variable "sub_name_caps" {}
variable "pcl_caps" {}
variable "app_caps" {}
variable "AZRegion_caps" {}
variable apptype_caps {}
variable rtrtypes_caps {}
variable "rt_last_names" {}
#variable "db_rt_last_names" {}
variable "routtable_rg" {}
variable "azure_route_table" {}
#variable "rt_snet_id" {}
variable "subnet_id" {}
variable "add_route_table" {}
#variable "firewall_private_ip_address" {}