variable "location" {}
variable "eventhub_sku" {}
variable "eventhub_capacity" {}
variable "Tags" {}
variable "Org" {}
variable "AZRegion" {}
variable "LZType" {}
variable "Env" {}
variable "eventhub_azurerm_resource_group" {}
variable "eventhub_partition_count" {}
variable "eventhub_message_retention" {}